apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: tindahan-wise
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
