apiVersion: v1
data:
  POSTGRES_DB: salesdb
  POSTGRES_HOST: pg-svc
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  name: transactions-db-config
